  nginx:
    image: nginx:1.15-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /home/ubuntu/dockertest/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/dockertest/sites-available:/etc/nginx/sites-available
      - /home/ubuntu/dockertest/archive/vilheor.hopto.org/:/etc/letsencrypt/live/vilheor.hopto.org
      - /home/ubuntu/dockertest/content1:/var/www/content1
      - /home/ubuntu/dockertest/content2:/var/www/content2
      - /home/ubuntu/dockertest/download:/var/www/download/
      - /home/ubuntu/dockertest/html:/var/www/html
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /home/ubuntu/dockertest/archive/vilheor.hopto.org/:/etc/letsencrypt/live/vilheor.hopto.org
      - ./data/certbot/www:/var/www/certbot
  apache:
    image: httpd:latest
    ports:
      - "9000:80"
    volumes:
      - /home/ubuntu/dockertest/html:/var/www/html
  php:
    image: php:7.2-fpm
    volumes:
      - ./html/phpinfo.php:/var/www/html/phpinfo.php
